### ISSUE TITLE
'should' and 'minimum_should_match'

### ISSUE THREAD

**Issue by brigand** [pictalk/eqm#1]
About this function...

https://github.com/pictalk/eqm/blob/5d000f327ca20cecec183e2e3246ea9dae623711/src/eqm.ts#L57-L61

It's dangerous to ever use `should` without `minimum_should_match: 1` or a [similar value].

> If the bool query is in a query context and has a must or filter clause then a document will match the bool query even if none of the should queries match  
> 
> This behavior may be explicitly controlled by settings the `minimum_should_match` parameter.
> - [Bool Query | Elasticsearch Reference [6.4] | Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html)

Maybe that should be set here, and in the rare case it'd be overridden, the caller can spread and override it?

```js
{
  ...should(x),
  minimum_should_match: 3
}
```

[similar value]: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html

**Comment by alexsasharegan** [comment]
That sounds smart! Besides this being experimental, it's largely for me to get a deeper understanding of Elasticsearch. So this is all still a bit new for me.
